Home/urls.py
from django.conf.urls import url
from . import views
app_name = 'homepage'

urlpatterns = [
    url(r'^$', views.index, name='home'),
]

Randomdrop/urls.py
from django.conf.urls import url
from . import views
app_name = 'RandomDrops'

urlpatterns = [
    url(r'^$', views.index, name='RandomDrops'),
]

django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^ZpX0Sea0wZy0EzUcH32m/', include(admin.site.urls)),
    url(r'^catnip/', include('Catnip.urls')),
    url(r'^ranks/', include('ranks.urls')),
    url(r'^Throwdown/', include('throwthursday.urls')),
    url(r'^drops/', include('Randomdrop.urls')),
    url(r'^goals/', include('goals.urls')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'', include('social_django.urls')),
    url(r'^$', include('Home.urls')),
]

Randomdrop/models.py
from __future__ import unicode_literals

from django.db import models

class RandomDrops(models.Model):
    Painted = 'P'
    Normal = 'N'
    Certified = 'C'
    PaintedCert = 'B'
    special = (
        (Painted, 'Painted'),
        (Normal, 'Normal'),
        (Certified, 'Certified'),
        (PaintedCert, 'Painted/Certified')
        )
    
    Body = 'BD'
    Wheel = 'WH'
    Boost = 'BO'
    Antenna = 'AN'
    Decal = 'DE'
    Topper = 'TO'
    type = (
        (Body, 'Body'),
        (Wheel, 'Wheel'),
        (Boost, 'Boost' ),
        (Antenna, 'Antenna'),
        (Decal, 'Decal'),
        (Topper, 'Topper')
        )
    
    Standard = 'ST'
    Black = 'BL'
    BurntSienna = 'BS'
    Cobalt = 'CO'
    Crimson = 'CR'
    ForestGreen = 'FG'
    Grey = 'GR'
    Lime = 'LI'
    Orange = 'OR'
    Pink = 'PI'
    Purple = 'PU'
    Saffron = 'SA'
    SkyBlue = 'SB'
    TitaniumWhite = 'TW'
    ItemColour = (
        (Standard, 'Standard'),
        (Black, 'Black'),
        (BurntSienna, 'Burnt Sienna'),
        (Cobalt, 'Cobalt'),
        (Crimson, 'Crimson'),
        (ForestGreen, 'Forest Green'),
        (Grey, 'Grey'),
        (Lime, 'Lime'),
        (Orange, 'Orange'),
        (Pink, 'Pink'),
        (Purple, 'Purple'),
        (Saffron, 'Saffron'),
        (SkyBlue, 'SkyBlue'),
        (TitaniumWhite, 'Titanium White')
        )
    
    Notcert = 'NO'
    Acrobat = 'AC'
    Aviator = 'Av'
    Goalkeeper = 'GK' 
    Guardian = 'GU'
    Juggler = 'JU'
    Paragon = 'PA'
    Playmaker = 'PL'
    Scorer = 'SC'
    ShowOff = 'SO' 
    Sniper = 'SN'
    Striker = 'ST'
    Sweeper =  'SW'
    Tactician = 'TA' 
    Turtle = 'TU'
    Victor = 'VI'
    ItemCert = (
        (Notcert, 'Notcert'),
        (Acrobat,'Acrobat' ),
        (Aviator, 'Aviator'),
        (Goalkeeper, 'Goalkeeper'),
        (Guardian, 'Guardian'),
        (Juggler, 'Juggler'),
        (Playmaker, 'Playmaker'),
        (Scorer, 'Scorer'),
        (ShowOff, 'ShowOff'),
        (Sniper, 'Sniper'),
        (Striker, 'Striker'),
        (Sweeper, 'Sweeper'),
        (Tactician, 'Tactician'),
        (Turtle, 'Turtle'),
        (Victor, 'Victor'),
        )
    Picture = models.CharField(max_length=1000)
    Name = models.CharField(max_length=100)
    type = models.CharField(max_length=2, choices=type, default=Body)
    type_special = models.CharField(max_length=1, choices=special, default=Normal)
    colour = models.CharField(max_length=2, choices=ItemColour, default=Standard)
    CertType = models.CharField(max_length=2, choices=ItemCert, default=Notcert)
    price = models.IntegerField()

Randomdrop/views.py
from django.shortcuts import render
from Catnip.models import Catnip
from .models import RandomDrops
def index(request):
    all_drops = RandomDrops.objects.order_by('-price')
    user_catnip = Catnip.objects.filter(name=request.user)
    return render(request, 'Randomdrop/index.html', {'all_drops': all_drops,'user_catnip':user_catnip,})

Randomdrop/templates/Randomdrop/index.html
{% extends 'home/base.html' %}

{% block body %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'drops/stylesheet.css' %}"/>
    <div id="allContent">
            <div class="col-sm-4 col-sm-offset-5">
            </div>
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading cam-heading">
                        <h4>Rocket League Drops</h4>
                    </div>
                        <div class="panel-body table-responsive">
                                    {% for x in all_drops %}
                                        <ul><img src={{ x.Picture }} alt={{ x.Name }} height = "110" width = "110" ></img></ul><ul><h3>{{ x.Name }}</h3><h5>Type: {{ x.get_type_display }}</h5><h5>&nbsp;&nbsp;&nbsp;{{ x.get_type_special_display }}</h5>{% if not x.get_colour_display == "Standard" %}<h5>&nbsp;&nbsp;&nbsp;{{ x.get_colour_display }}</h5> {% endif %}{% if not x.get_CertType_display == "Notcert" %}<h5>&nbsp;&nbsp;&nbsp;{{ x.get_CertType_display }}</h5> {% endif %}<h5>Price: {{ x.price }} Keys</h5></ul>{% endfor %}
                        </div>
                </div>
            </div>
    </div>
    <p class="signoff">Designed by Waypalm, Fixed by DukeKero</p>
{% endblock %}